# Generated by Django 5.0.4 on 2024-05-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_photo_url_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True),
        ),
    ]
