# Generated by Django 5.0.4 on 2024-05-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_announcements_events_notifications_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='date',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='time',
        ),
    ]
