# Generated by Django 5.0.4 on 2024-05-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_announcements_date_remove_announcements_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
