# Generated by Django 5.0.4 on 2024-05-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_announcements_date_remove_announcements_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
