# Generated by Django 5.0.4 on 2024-05-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
