# Generated by Django 3.2 on 2024-05-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_events_time'),
        ('posts', '0007_events_time'),
    ]

    operations = [
    ]
